# Numpy로 연산하기

## Vector & Scalar 사이 연산
벡터의 각 원소에 대해 연산 진행

$$ x=\begin{pmatrix}
1 \\
2\\
3 
\end{pmatrix}, c=5 $$

In [22]:
import numpy as np

In [23]:
x=np.array([1,2,3])
c=5 #np.array([5])

print("add:{}".format(x+c))
print("sub:{}".format(x-c))
print("mul:{}".format(x*c))
print("div:{}".format(x/c))

add:[6 7 8]
sub:[-4 -3 -2]
mul:[ 5 10 15]
div:[0.2 0.4 0.6]


## Vector & Vector 사이 연산
벡터의 **같은 인덱스** 끼리 연산 진행

$$ y=\begin{pmatrix}
1 \\
3\\
5 
\end{pmatrix}, z=\begin{pmatrix}
2 \\
9\\
20 
\end{pmatrix} $$

In [24]:
y=np.array([1,3,5])
z=np.array([2,9,20])

print("add:{}".format(y+z))
print("sub:{}".format(y-z))
print("mul:{}".format(y*z))
print("div:{}".format(y/z))

add:[ 3 12 25]
sub:[ -1  -6 -15]
mul:[  2  27 100]
div:[0.5        0.33333333 0.25      ]


## Array Indexing
: 특정 인덱스에 있는 원소를 갖고 오고 싶을때 인덱싱 이용

python의 list와 유사하게 진행

$$ W=\begin{pmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12 
\end{pmatrix}$$

In [25]:
W=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print("1행 2열 : ",W[1][2])

1행 2열 :  7


## Arrary Slicing
: 특정 범위의 원소를 갖고 오고 싶을때 슬라이싱 이용

python의 list와 유사하게 진행

$$ W=\begin{pmatrix}
1 & 2 & 3 & 4 \\
5 & 6 & 7 & 8\\
9 & 10 & 11 & 12 
\end{pmatrix}$$

In [26]:
W=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

W[1:3,1:3] #2행~3행, 2열~3열

array([[ 6,  7],
       [10, 11]])

In [27]:
W[:, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## Array Broadcasting
numpy가 연산을 진행하는 특수한 방법

같은 Type의 데이터에 대해서만 연산 가능


### 1. M X N , M X 1

In [32]:
A=np.array([[1,2,3], [4,5,6], [7,8,9]])
B=np.array([1,-1,2])

B=B[:, None]
print(A+B)

[[ 2  3  4]
 [ 3  4  5]
 [ 9 10 11]]


### 2. M X N , 1 X N

In [29]:
C=np.array([0,2,-1])

print(A*C)

[[ 0  4 -3]
 [ 0 10 -6]
 [ 0 16 -9]]


### 3. M X 1, 1 X N

In [31]:
X=np.array([1,2,3]) #열벡터로 바꿔줘야함
X=X[:, None] #transpose

Y=np.array([2,0,-2])
print(X+Y)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


- - - - - - - - - - - - - - - - - - -

# Numpy와 선형대수

## 영벡터(행렬)
+ 모든원소가 0
+ np.zeros(dim)을 통해 생성, dim은 값 or 튜플(,)

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [37]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

## 일벡터(일행렬)
+ 모든 원소가 1
+ np.ones(dim)을 통해 생성, dim은 값 or 튜플(,)

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## 대각행렬(diagonal matrix)
+ 대각원소를 제외한 성분이 0
+ np.diag((main_diagonal))을 통해 생성

In [41]:
np.diag((1,3,5))

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

## 항등행렬(Identity matrix)
+ 대각원소가 1인 대각행렬
+ np.eye(n, dtype)를 통해 생성 (n은 사이즈, dtype은 데이터 타입(int, uint, float, complex, ...))
+ default dtype=float

In [45]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

## 행렬곱(dot product)
+ 행렬간의 곱연산
+ np.dot() or @를 통해 연산 수행

In [46]:
mat_1=np.array([[1,2], [3,4]])
mat_2=np.array([[5,6], [7,8]])

mat_1.dot(mat_2) # mat_1 @ mat_2

array([[19, 22],
       [43, 50]])

## 트레이스(trace)
+ 대각 원소의 합
+ np.trace()를 통해 구할 수 있음

In [47]:
arr=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr.trace()

18

In [48]:
np.eye(2, dtype=int).trace() #항등행렬의 trace는 차원 수

2

## 행렬식(Determinant)
+ 행렬을 대표하는 값들 중 하나
+ np.linalg.det()을 통해 계산

In [50]:
arr=np.array([[1,4,7], [2,5,8], [3,6,9]]) 
np.linalg.det(arr)#det=0 이므로 각 열벡터끼리 종속(dependent)

0.0

## 역행렬(Inverse matrix)
+ 행렬 A에 대해 AB=BA=I를 만족하는 B=A^{-1}
+ np.linalg.inv()으로 계산

In [52]:
mat=np.array([[1,4],[2,3]])
mat_inv=np.linalg.inv(mat)
mat_inv

array([[-0.6,  0.8],
       [ 0.4, -0.2]])

In [53]:
mat@mat_inv

array([[ 1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  1.00000000e+00]])

## 고유값과 고유벡터(eigenvalue and eigenvector)
+ 정방행렬 A에 대해 $ Ax= \lambda x$를 만족하는 상수 $\lambda$(고유값), 이에 대응하는 벡터(고유벡터)
+ np.linalg.eig()으로 계산

In [55]:
mat=np.array([[2,0,2], [1,1,-2], [0,0,1]])
mat

array([[ 2,  0,  2],
       [ 1,  1, -2],
       [ 0,  0,  1]])

In [56]:
np.linalg.eig(mat)

(array([1., 2., 1.]),
 array([[ 0.00000000e+00,  7.07106781e-01, -1.11022302e-16],
        [ 1.00000000e+00,  7.07106781e-01,  1.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  5.55111512e-17]]))

### validation


In [58]:
eig_val, eig_vec=np.linalg.eig(mat)
eig_val

array([1., 2., 1.])

In [59]:
eig_vec

array([[ 0.00000000e+00,  7.07106781e-01, -1.11022302e-16],
       [ 1.00000000e+00,  7.07106781e-01,  1.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  5.55111512e-17]])

In [60]:
mat @ eig_vec[:, 0] #AX
#eig_vec : 열벡터이니까

array([0., 1., 0.])

In [62]:
eig_val[0] * eig_vec[:,0] #(lambda)x

array([0., 1., 0.])