In [2]:
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np

from sklearn.linear_model import LinearRegression

model=LinearRegression(fit_intercept=True)

In [5]:
N=1000 #사실 큰 수는 아님
M=3
rng=np.random.RandomState(1)
rng.rand(N,M).shape #(1000,3)

X=10*rng.rand(N,M)
np.dot(X, [1.5, -2., 1.]).shape #(1000,)

(1000,)

In [6]:
rng=np.random.RandomState(1)
X=10*rng.rand(N,M)
y=0.5+np.dot(X, [1.5, -2., 1.])

model.fit(X,y)
print(model.intercept_)
print(model.coef_)

0.499999999999968
[ 1.5 -2.   1. ]


## Normal Equations

In [8]:
import numpy.linalg as LA 

normal_equation_sol=LA.inv(X.T@X)@X.T@y

normal_equation_sol

array([ 1.52825484, -1.96886193,  1.03058857])

## Small Memory Normal Equations (Online)

In [9]:
A=np.zeros([M,M])
b=np.zeros([M,1])

In [12]:
for i in range(N):
  A=A+X[i, np.newaxis].T@X[i, np.newaxis] # A update (outer product)
  b=b+X[i, np.newaxis].T*y[i] # b update
sol=LA.inv(A)@b
sol

array([[ 1.52825484],
       [-1.96886193],
       [ 1.03058857]])

계산하는 방법이 다르지만, online의 경우 메모리를 적게 사용(장점)

## SGD


In [13]:
w=np.zeros([M,1])

In [14]:
eta=0.001 # learning rate (paramter)
n_iter=500 # iterations

In [16]:
for i in range(n_iter):
  i=i%N
  neg_gradient=(y[i]-w.T@X[i, np.newaxis].T)*X[i, np.newaxis].T #=(tn-w.T@X)*X.T
  w=w+eta*neg_gradient # w(i+1)=w(i)-eta*grad = w(i)+eta*grad
print(w)

[[ 1.51033015]
 [-1.93792375]
 [ 1.0123695 ]]
