In [8]:
import numpy as np

In [15]:
# mxn행렬
A=np.array([[3,1,1], [1,-2,-1], [1,1,1]])
print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [16]:
# b (m-벡터)
b=np.array([4,1,2])
print(b)
print(np.shape(b))

[4 1 2]
(3,)


In [17]:
# 행렬 A의 역행렬
A_inv=np.linalg.inv(A)
print(A_inv)
print(np.shape(A_inv))

[[ 5.00000000e-01 -7.40148683e-17 -5.00000000e-01]
 [ 1.00000000e+00 -1.00000000e+00 -2.00000000e+00]
 [-1.50000000e+00  1.00000000e+00  3.50000000e+00]]
(3, 3)


In [18]:
# Ax=b의 해 구하기
x=A_inv @ b # @ = matmul (행렬 곱)

print(x)
print(np.shape(x))

[ 1. -1.  2.]
(3,)


In [21]:
# 결과 검증하기
bb= A @ x

print(np.shape(bb))
print(bb)

# 검증할때, 실제 b와 bb간의 차이의 벡터 놈을 구해서 10^-3보다 작으면 ok
# 10^-3의 오차는 ok -> 차이 없다고 본다.
if np.linalg.norm(b-bb)<1e-3:
    print("OK")
else:
    print("something wrong")

(3,)
[4. 1. 2.]
OK
